### ISSUE TITLE
Error 404 on NetApp SnapCenter 4.7 Release Notes

### ISSUE THREAD

**Issue by BenHarrod** [NetAppDocs/snapcenter-47#5]
Page: [SnapCenter Software documentation](https://docs.netapp.com/us-en/snapcenter-47/index.html)

**Comment by netapp-nsriram** [comment]
Hello,

This is fixed now.  Please check the following links: 

https://docs.netapp.com/us-en/snapcenter-47/index.html

https://library.netapp.com/ecm/ecm_download_file/ECMLP2883299

I assume that my response to your query was satisfactory. Thus, closing the issue. If you have any further query, feel free to open an issue.

Regards,
Nirupama
